<h1> Lasso Regression (numpy) </h1>

Lasso Regression의 Cost 함수를 최소화해서 가중치를 구하기!

Lasso Regression 식이 미분 불가능(absolute value 때문)
하기 때문에, gradient descent 대신에 coordinate descent 라는 방법을
사용한다.

매 iteration에서는 weight i만 제외하고 다른 모든 가중치들은
고정값으로 두고, objective를 최소화하는 i를 찾는 방식이다.

이 방법으로는 다음 값을 찾게 된다.

argmin_{w[i]} [ SUM[ (prediction - output)^2 ] + lambda*( |w[1]| + ... + |w[k]|) ]


매 w[i]값을 최적화하는 공식은 다음과 같다.

               ┌ (ro[i] + lambda/2)     if ro[i] < -lambda/2 
        w[i] = ├ 0                      if -lambda/2 <= ro[i] <= lambda/2 
               └ (ro[i] - lambda/2)     if ro[i] > lambda/2 
where
ro[i] = SUM[ [feature_i]*(output - prediction + w[i]*[feature_i]) ].



Note that we do not regularize the weight of the constant feature (intercept) w[0], so, for this weight, the update is simply:

w[0] = ro[i]

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_boston
from sklearn import preprocessing

In [4]:
np.random.seed(42)

In [5]:
X, y = load_boston(return_X_y=True)

X = pd.DataFrame(X)

X['constant'] = 1

In [6]:
display(X)

0     1      2    3      4      5     6       7    8      9    10  \
0    0.00632  18.0   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1    0.02731   0.0   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2    0.02729   0.0   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3    0.03237   0.0   2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4    0.06905   0.0   2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   
..       ...   ...    ...  ...    ...    ...   ...     ...  ...    ...   ...   
501  0.06263   0.0  11.93  0.0  0.573  6.593  69.1  2.4786  1.0  273.0  21.0   
502  0.04527   0.0  11.93  0.0  0.573  6.120  76.7  2.2875  1.0  273.0  21.0   
503  0.06076   0.0  11.93  0.0  0.573  6.976  91.0  2.1675  1.0  273.0  21.0   
504  0.10959   0.0  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0  21.0   
505  0.04741   0.0  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0  21.0   

         11    12  constant  
0    396.90  4.98         1  
1    396.90  9.14         1  
2    392.83  4.03         1  
3    394.63  2.94         1  
4    396.90  5.33         1  
..      ...   ...       ...  
501  391.99  9.67         1  
502  396.90  9.08         1  
503  396.90  5.64         1  
504  393.45  6.48         1  
505  396.90  7.88         1  

[506 rows x 14 columns]

In [7]:
X = X.iloc[0:100,0:5]
y = pd.DataFrame(y)
y = y.iloc[0:100]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [8]:
# def normalize_features(feature_matrix):
#     norms = np.linalg.norm(feature_matrix, axis=0)
#     normalized_features= feature_matrix/norms
#     return (normalized_features, norms)

In [11]:

scaler = preprocessing.MinMaxScaler().fit(X_train)
                                      
print(scaler.scale_)                                      


[1. 1. 1. 1. 1.]


In [12]:
X_train = pd.DataFrame(scaler.transform(X_train))

In [13]:

print(X_train)

X_test = pd.DataFrame(scaler.transform(X_test))


# add constant

X_train = X_train.to_numpy()

y_train = y_train.to_numpy()


X_test = X_test.to_numpy()

y_test = y_test.to_numpy()

           0      1         2    3         4
0   0.064950  0.125  0.498601  0.0  0.900000
1   0.134859  0.000  0.431469  0.0  0.357143
2   0.027357  0.000  0.262238  0.0  0.364286
3   0.474850  0.000  0.517483  0.0  1.000000
4   0.009473  0.280  1.000000  0.0  0.471429
..       ...    ...       ...  ...       ...
65  0.084866  0.250  0.306993  0.0  0.392857
66  0.090769  0.000  0.704196  0.0  0.107143
67  0.390415  0.000  0.517483  0.0  1.000000
68  0.017777  0.280  1.000000  0.0  0.471429
69  0.018615  0.210  0.342657  0.0  0.292857

[70 rows x 5 columns]


In [14]:
print(X_train)

[[6.49504133e-02 1.25000000e-01 4.98601399e-01 0.00000000e+00
  9.00000000e-01]
 [1.34859494e-01 0.00000000e+00 4.31468531e-01 0.00000000e+00
  3.57142857e-01]
 [2.73570866e-02 0.00000000e+00 2.62237762e-01 0.00000000e+00
  3.64285714e-01]
 [4.74850239e-01 0.00000000e+00 5.17482517e-01 0.00000000e+00
  1.00000000e+00]
 [9.47336827e-03 2.80000000e-01 1.00000000e+00 0.00000000e+00
  4.71428571e-01]
 [1.01612036e-02 0.00000000e+00 1.00699301e-01 0.00000000e+00
  4.28571429e-01]
 [1.88779530e-02 8.00000000e-01 1.83916084e-01 0.00000000e+00
  0.00000000e+00]
 [1.39067796e-02 8.00000000e-01 1.83916084e-01 0.00000000e+00
  0.00000000e+00]
 [3.16216656e-02 0.00000000e+00 3.65034965e-01 0.00000000e+00
  7.21428571e-01]
 [6.50523380e-01 0.00000000e+00 5.17482517e-01 0.00000000e+00
  1.00000000e+00]
 [1.28919098e-01 0.00000000e+00 4.31468531e-01 0.00000000e+00
  3.57142857e-01]
 [1.00000000e+00 0.00000000e+00 5.17482517e-01 0.00000000e+00
  1.00000000e+00]
 [8.18836683e-02 1.25000000e-01 4.986013

In [15]:
# def get_numpy_data(data_sframe, features, output):
#     data_sframe['constant'] = 1 # this is how you add a constant column to an SFrame
#     # add the column 'constant' to the front of the features list so that we can extract it along with the others:
#     features = ['constant'] + features # this is how you combine two lists
#     # select the columns of data_SFrame given by the features list into the SFrame features_sframe (now including constant):
#     features_sframe = data_sframe[features]  
#     # the following line will convert the features_SFrame into a numpy matrix:
#     feature_matrix = features_sframe.to_numpy()
#     # assign the column of data_sframe associated with the output to the SArray output_sarray
#     output_sarray = data_sframe['price'] 
#     # the following will convert the SArray into a numpy array by first converting it to a list
#     output_array = output_sarray.to_numpy()
#     return(feature_matrix, output_array)

In [16]:
X_train.shape

(70, 5)

In [17]:

def predict_output(feature_matrix, weights):
    # assume feature_matrix is a numpy matrix containing the features as columns and weights is a corresponding numpy array
    # create the predictions vector by using np.dot()
    predictions = np.dot(feature_matrix,weights)
    return(predictions)

# Assign some initial weight

In [18]:
weights = np.array([1., 2., 1., 1., 1.])

prediction = predict_output(X_train, weights)
prediction

array([1.71355181, 0.92347088, 0.65388056, 1.99233276, 2.04090194,
       0.53943193, 1.80279404, 1.79782286, 1.1180852 , 2.1680059 ,
       0.91753049, 2.51748252, 1.73048507, 0.55387199, 2.10662597,
       1.96282462, 1.00750884, 2.0345721 , 1.26029837, 1.90277035,
       1.97811958, 0.5410077 , 1.99934242, 1.187419  , 1.77218665,
       1.15082654, 1.69530542, 0.52773651, 1.13888909, 0.8613628 ,
       1.79006015, 0.5204557 , 1.81368631, 0.87975582, 1.10249364,
       0.72899345, 0.89788966, 0.77754837, 1.2987171 , 0.55311537,
       1.16796614, 0.85979609, 1.28792434, 0.93885338, 0.5287535 ,
       2.1338668 , 1.17500082, 2.37689523, 2.04977502, 1.25592749,
       1.27044707, 0.6496535 , 1.12807132, 2.1358152 , 0.95837313,
       1.08052668, 2.0417631 , 0.95836062, 2.12704843, 0.66273488,
       0.85279613, 1.1648959 , 0.65046015, 1.00248765, 2.29172871,
       1.28471652, 0.90210791, 1.90789784, 2.04920599, 1.07412981])

Compute the values of ro[i] for each feature in this simple model, using the formula given above, using the formula:

ro[i] = SUM[ [feature_i]*(output - prediction + w[i]*[feature_i]) ]

In [19]:
def calculate_ro(num_features, feature_matrix,output,prediction, weights):
    for i in range(num_features):
        ro_i = (feature_matrix[:,i]*(output - prediction+ weights[i]*feature_matrix[:,i])).sum()
        #ro_arr.append(ro_i)
        print (ro_i)
        print (i)
    return 0

In [20]:
ro = calculate_ro(5, X_train,y_train,prediction, weights)
ro

16746.76814407907
0
13093.084983762517
1
43196.92152239164
2
0.0
3
54758.44405333633
4


0

In [21]:
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)
print(type(X_train))

(70, 5) (70, 1) (30, 5) (30, 1)
<class 'numpy.ndarray'>


In [22]:
# def lasso_coordinate_descent_step(num_features, feature_matrix, output, weights, l1_penalty):
#     prediction = predict_output(feature_matrix, weights)
    
#     for i in range(num_features+1):
        
#         ro_i = (feature_matrix[:i]*(output - prediction + weights[i]*feature_matrix[:i])).sum()
#         if i==0 :
#             new_weight_i = ro_i
#         elif ro_i < -l1_penalty/2.:
#             new_weight_i = (ro_i + (l1_penalty/2))
#         elif ro_i > l1_penalty/2.:
#             new_weight_i = (ro_i - (l1_penalty/2))
#         else :
#             new_weight_i = 0.
#     return new_weight_i

In [23]:
def lasso_coordinate_descent_step(num_features, feature_matrix, output, weights, l1_penalty):
    # compute prediction
    prediction = predict_output(feature_matrix, weights)
    #z_i= (feature_matrix*feature_matrix).sum()

    for i in range(num_features+1):
    # compute ro[i] = SUM[ [feature_i]*(output - prediction + weight[i]*[feature_i]) ]
        ro_i = (feature_matrix[:,i]*(output - prediction+weights[i]*feature_matrix[:,i])).sum()
        if i == 0: # intercept -- do not regularize
            new_weight_i = ro_i 
        elif ro_i < -l1_penalty/2.:
            new_weight_i = (ro_i +(l1_penalty/2))
        elif ro_i > l1_penalty/2.:
            new_weight_i = (ro_i -(l1_penalty/2))
        else:
            new_weight_i = 0.
    return new_weight_i

In [24]:
# should print 0.425558846691
import math
print (lasso_coordinate_descent_step(1, np.array(([3./math.sqrt(13),1./math.sqrt(10)],[2./math.sqrt(13),3./math.sqrt(10)])),np.array([1., 1.]), np.array([1., 4.]), 0.1))


0.4255588466910251


# Cyclical coordinate descent
하나의 가중치에 대해선 cost function을 optimize했으니, 이것을 반복해서
가중치의 변화가 일정 threshold치 이하일 경우에는 가중치 변화를 멈출 것이다.

매 이터레이션마다의 다음과 같이 실행한다. <br>
Loop over features in order and perform coordinate descent, measure how much each coordinate changes.
After the loop, if the maximum change across all coordinates is falls below the tolerance, stop. Otherwise, go back to step 1.
Return weights

In [25]:
def lasso_cyclical_coordinate_descent(feature_matrix, output, initial_weights, 
                                      l1_penalty, tolerance):
    condition = True
    max_change=0
    while (condition == True):  
        max_change=0
        for i in range (len(initial_weights)):
            #max_change=0
            old_weight_i= initial_weights[i]
            initial_weights[i] =lasso_coordinate_descent_step(i,
                                                      feature_matrix, output, 
                                                      initial_weights, l1_penalty)
            coordinate_change = abs(old_weight_i - initial_weights[i])
            if coordinate_change>max_change:
                max_change = coordinate_change
                print (max_change)
        if (coordinate_change < tolerance):
            condition = False
    return initial_weights        


argument값들을 정해주자.


In [35]:

initial_weights = np.zeros(5) # constant의 1열을 포함한 feature column수로 줘야 한다.
l1_penalty = 1e8
tolerance = 1.0

In [36]:
weights = lasso_cyclical_coordinate_descent(X_train, y_train,
                                            initial_weights, l1_penalty, tolerance)

weights

17869.546841585274


array([17869.54684159,     0.        ,     0.        ,     0.        ,
           0.        ])

In [37]:
prediction = predict_output(X_train, weights)

rss_errors = (y_train - prediction)
        # Then square and add them up
rss_error_sq= rss_errors*rss_errors
        #RSS = RSS_ + str(degree)
RSS=rss_error_sq.sum()
print (RSS)

#rss_errors

128564307162.10153


## Evaluating LASSO fit with more features

In [ ]:
X, y = load_boston(return_X_y=True)

X = pd.DataFrame(X)
X['constant']=1

y = pd.DataFrame(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)




In [ ]:
scaler_2 = preprocessing.MinMaxScaler().fit(X_train)
print(scaler_2.mean_)                                      
print(scaler_2.scale_)                                      

X_train = pd.DataFrame(scaler.transform(X_train))
print(X_train)

X_test = pd.DataFrame(scaler.transform(X_test))


# add constant

X_train = X_train.to_numpy()

y_train = y_train.to_numpy()


X_test = X_test.to_numpy()

y_test = y_test.to_numpy()

In [ ]:
weights = np.array([1., 4., 1., 2.,3., 4., 1., 1., 1., 3., 1., 2., 1., 4. ])

prediction = predict_output(X_train, weights)
prediction

In [ ]:
ro = calculate_ro(14, X_train,y_train,prediction, weights)
ro

In [ ]:
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)
print(type(X_train))

In [ ]:
initial_weights = np.zeros(14) # constant의 1열을 포함한 feature column수로 줘야 한다.
l1_penalty =1e9
tolerance = 1.0

In [ ]:
weights = lasso_cyclical_coordinate_descent(X_train, y_train,
                                            initial_weights, l1_penalty, tolerance)

weights

In [ ]:
prediction = predict_output(X_train, weights)

rss_errors = (y_train - prediction)
        # Then square and add them up
rss_error_sq= rss_errors*rss_errors
        #RSS = RSS_ + str(degree)
RSS=rss_error_sq.sum()
print (RSS)

#rss_errors